# Site settings
title: Stochastic Resonance
email:
description: > # this means to ignore newlines until "baseurl:"
  Content is forthcoming.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://mouzak.xyz" # the base hostname & protocol for your site
twitter_username:
github_username:  mouzak

# Build settings
markdown: kramdown
